---
# Per environment values which override defaults in hmpps-release-scheduler-api/values.yaml

generic-service:
  ingress:
    host: release-scheduler-api.hmpps.service.justice.gov.uk

  env:
    SPRING_PROFILES_ACTIVE: prod
    SENTRY_ENVIRONMENT: prod

generic-prometheus-alerts:
  alertSeverity: move-and-improve-alerts
  rdsAlertsDatabases:
    cloud-platform-3fd75c7a01b5cee5: "Release Scheduler API DB"
    rdsAlertsConnectionThreshold: 100
  sqsOldestAlertQueueNames:
    - "hmpps-release-scheduler-prod-domain_events_queue"
  sqsAlertsOldestThreshold: 10
  sqsNumberAlertQueueNames:
    - "hmpps-release-scheduler-prod-domain_events_dlq"
  sqsAlertsTotalMessagesThreshold: 1
  applicationCronJobStatusFailedWindowMinutes: 15
