generic-service:
  replicaCount: 2

  ingress:
    host: release-scheduler-api-preprod.hmpps.service.justice.gov.uk

  env:
    SPRING_PROFILES_ACTIVE: dev
    SENTRY_ENVIRONMENT: dev

  generic-prometheus-alerts:
    businessHoursOnly: true
    alertSeverity: move-and-improve-alerts-non-prod
    rdsAlertsDatabases:
      cloud-platform-31346e935fd40db4: "Release Scheduler API DB"
      rdsAlertsConnectionThreshold: 100
    sqsOldestAlertQueueNames:
      - "hmpps-release-scheduler-dev-domain_events_queue"
    sqsAlertsOldestThreshold: 10
    sqsNumberAlertQueueNames:
      - "hmpps-release-scheduler-dev-domain_events_dlq"
    sqsAlertsTotalMessagesThreshold: 1
    applicationCronJobStatusFailedWindowMinutes: 15
